services:
  query-side-redis:
    image: redis:latest
    ports:
      - 6379:6379
  command-side-postgres:
    image: postgres
    environment:
      POSTGRES_DB: blog
      POSTGRES_USER: lenhatthanh
      POSTGRES_PASSWORD: lenhatthanh
    ports:
      - "5555:5432"
    volumes:
      - command-side-postgres:/var/lib/postgresql/data
volumes:
  command-side-postgres: