services:
  query-side-redis:
    image: "redis/redis-stack:edge"
    ports:
      - "6379:6379"
    environment:
      - "REDIS_ARGS=--appendonly yes"
    volumes:
      - ./data:/data
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
  command-side-postgres:
    image: postgres
    environment:
      POSTGRES_DB: blog
      POSTGRES_USER: lenhatthanh
      POSTGRES_PASSWORD: lenhatthanh
    ports:
      - "5555:5432"
    volumes:
      - command-side-postgres:/var/lib/postgresql/data
volumes:
  command-side-postgres:
