name: unit-tests

on:
  push:
    branches:
      - main
      - 'PBI-**'
jobs:
  command-side-unit-test:
    runs-on: ubuntu-latest
    env:
      SPRING_DATASOURCE_URL: jdbc:h2:mem:blog
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: ''
    steps:
      - name: Setup H2 database
        run: |
          cd command-side
          mvn h2:create
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: '17'
      - name: Command side test
        working-directory: command-side
        run: mvn -Dspring.profiles.active=test test
  query-side-unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: '17'
      - name: Query side test
        run: |
          cd query-side
          mvn test
