name: unit-tests

on:
  push:
    branches:
      - main
      - 'PBI-**'
jobs:
  command-side-unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: '17'
      - name: Command side test
        working-directory: command-side
        run: |
          mvn clean package
          java -jar -Dspring.profiles.active=test target/command-side-0.0.1-SNAPSHOT.jar
  query-side-unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: '17'
      - name: Query side test
        run: |
          cd query-side
          mvn test
