name: unit-tests-with-java-17

on:
  push:
    branches:
      - main
      - 'PBI-**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: '17'

      - name: Build and test Spring Boot application
        run: ./mvnw clean test
