name: unit-tests-with-java-17

on:
  push:
    branches:
      - main
      - 'PBI-**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: '17'

      - name: Command side test
        run: |
          cd command-side
          mvn test

      - name: Query side test
        run: |
          cd ../query-side
          mvn test
